### ISSUE TITLE
[❓, 🚀] Use `C` code(`Cython` or `mypyc`) instead of full `CPython` ?

### ISSUE THREAD

**Issue by MaximZayats** [Neoteroi/rodi#19]
Hi, @RobertoPrevato!
I've been testing different ways to run `rodi`: `CPython`, `PyPy`, `mypyc`. And I got interesting results :)
1) `CPython3.10`: 0.28 - 0.33 average
2) `mypyc 0.950`: 0.13 - 0.16 average
3) `PyPy3.9`: 0.08-0.09 average

[Benchmark](https://github.com/MaximZayats/rodi-mypyc/blob/main/bench.py)

To run `mypyc` I fixed couple `mypy` issues: [commit](https://github.com/MaximZayats/rodi-mypyc/commit/2bb16b0767a7dd2fc11e2ef0da0cbb2666b6838b)

Do you think this performance boost matters ?
Should some code be rewritten using 'Cython'?

Benchmark code:
```python
from timeit import timeit

from rodi import Container


class A:
    pass


class B:
    def __init__(self, a: A):
        self.a = a


class Dog:
    def __init__(self, b: B):
        self.b = b


class Cat:
    def __init__(self, dog: Dog):
        self.dog = dog


container = Container()
container.add_transient(A)
container.add_transient(B)
container.add_transient(Dog)
container.add_transient(Cat)

services = container.build_provider()  # --> validation, generation of functions

cat = services.get(Cat)

print(
    "services.get(Cat)",
    timeit(
        "do()",
        globals={"do": lambda: services.get(Cat)},
        number=100_000
    )
)

# Before mypyc: 0.28 - 0.33 average
# After mypyc:  0.13 - 0.16 average (mypyc rodi)
# Diff: ~2 times
```

`mypy --version -> mypy 0.950 (compiled: yes)`

**Comment by RobertoPrevato** [comment]
Hi @MaximZayats Thank You for this contribution!
Yes, I find this very interesting. 🎉 

Using mypyc or Cython comes at a price though, for example that the package will require a bit more complex CI / CD pipelines (like BlackSheep's one), to distribute wheels. Therefore before opting-in for this, I wish to verify what is the performance boost of only resolving the services, without the `build_provider()` step.

Because the performance improvements of building a service provider is not so interesting, because this action is done rarely - generally once at application start-up.

I never tried mypyc and I'm going to try it, cloning your fork.

**Comment by RobertoPrevato** [comment]
It looks very promising, if you make a pull request I'll be happy to merge your changes with type annotations.

I need a bit of time to consider whether to change the distribution package, though.

**Comment by RobertoPrevato** [comment]
Hi @MaximZayats 
Thank You again for your help. Sorry for taking several months, I struggled to find time for my open source projects lately. I am working to include `mypyc` in `1.1.4` - I am still resolving a couple of issues related to distributing compiled libraries instead of Python source code.

Anyway I can close this issue now, since your contribution has been merged to `main`.

**Comment by RobertoPrevato** [comment]
Hi @MaximZayats 
One more thing. I just noticed that, probably because I squashed the commit with the pull request or because I forked your fork to apply minor changes for linters, I lost track of your contribution in the git history. I will try to re-write the history of `main` to give you credit.

**Comment by RobertoPrevato** [comment]
Done! Quel che è giusto, è giusto.

**Comment by MaximZayats** [comment]
Hi @RobertoPrevato 
Thanks for the release!
I tried to test the new version, but realized that it has not been released on pypi yet.
When do you plan to release it ?

**Comment by RobertoPrevato** [comment]
Hi @MaximZayats 
As soon as possible, as I wrote before _I am still resolving a couple of issues related to distributing compiled libraries instead of Python source code._
If you take a look to the GitHub Workflows, you'll see that I already modified it to build wheels for several distributions of Linux, (manylinux Docker image), Mac OS, Windows. But I am still missing the step to:
- create a pure Python distribution wheel
- remove the Python source code from wheels that has the extension (I thought the compiled version would take precedence when installed, instead the source code takes precedence)

Nothing complex, I only need to apply a small change to the `setup.py` file and the wheel building steps.

**Comment by q0w** [comment]
Maybe implement acustom pep517 backend with `build_wheel` function?

**Comment by RobertoPrevato** [comment]
Thanks for the recommendation, yes I think it's high time for me to start using `pyproject.toml` 😄 
Another option I am considering is to distribute a [stub-only package ](https://peps.python.org/pep-0561/#stub-only-packages), alongside the C version of `rodi`.

**Comment by RobertoPrevato** [comment]
I write an update here. I tried `pyproject.toml` using `hatch`, and they are capable of generating a wheel without `__init__.py` (necessary to distribute the optimized version) 🎉 . I verified this on a test package, a "stub-only" package used to distribute a single `.pyi` file. Apparently it is a limitation of `bdist_wheel` that it cannot generate a `wheel` respecting source code exclusion.

I'm going to improve this project to use `pyproject.toml` and the workflow accordingly.

**Comment by RobertoPrevato** [comment]
Hi @MaximZayats and @q0w 
Finally I am not going to distribute wheels having compiled versions of `rodi`, because the tests suite does not pass with the compiled version, it goes into segmentation fault. Anyway `mypyc` is alpha software and they don´t recommend it for [general production use](https://mypyc.readthedocs.io/en/latest/introduction.html).

I was already planning to create an abstraction layer around the protocol of `rodi`, to support different kinds of DI containers in `blacksheep`. When that is done, I might distribute an alternative **alpha** package containing extensions built with `mypyc`, under a different namespace.

Thank You again for the interesting input! I learnt several new things thanks to you.
