### ISSUE TITLE
Inner dependency not resolved when "parent" dependency extends from a protocol

### ISSUE THREAD

**Issue by lucas-labs** [Neoteroi/rodi#45]
Hi there! It's me bothering you again haha

I found an issue trying to provide a class that implements a protocol and at the same time depends on another class.

The code:

```python
class P(Protocol):
    def foo(self): ...

class Dependency: 
    pass

class Impl(P):
    dependency: Dependency # <-- should inject this, but it doen't
    def foo(self): pass

container = Container()
container.register(Dependency)
container.register(Impl)

resolved = container.resolve(Impl)
assert isinstance(resolved.dependency, Dependency) # <-- 💥 this fails, resolved.dependency is None
```

I tracked the issue down to the following line:

https://github.com/Neoteroi/rodi/blob/6043b5be9ffd48d5b7b7c9d2ce231106b54dab0e/rodi/__init__.py#L608

Apparently (never noticed until now) if a class extending from a protocol doesn't define its own `__init__`, then `Protocol` replaces it with the function `typing._no_init_or_replace_init`. Which means the above `if` block is not reached in this case, and the attributes of the class are being ignored during resolution.

The following change would fix it:

```diff
+ from typing import _no_init_or_replace_init

- if getattr(concrete_type, "__init__") is object.__init__:
+ if getattr(concrete_type, "__init__") in [
+    object.__init__,
+    _no_init_or_replace_init,
+]
```

But the problem is that the `typing` library doesn't really expose `_no_init_or_replace_init` in its `__all__` section... so, accessing `typing._no_init_or_replace_init` is a bit obscure, we are not supposed to do it.

Can you think in a cleaner way to do it?

**Comment by RobertoPrevato** [comment]
Hi @lucas-labs 
You are not bothering, no worries! Or, if this is the way you bother, I welcome it 😄 
The issue with `Protocol` and its `__init__` method was discussed here:

https://github.com/Neoteroi/rodi/issues/31#issuecomment-1461537538

One issue here is that I never took the time to work on dedicated documentation for `rodi` at https://www.neoteroi.dev/ - otherwise this would be a documented "limitation of the library". But I am digressing.

Your idea seems good, I don't mind reading private properties if it is for a good cause - the important thing is that this part is tested, so if anything changes in future versions of Python, we discover immediately that some extra logic is needed.

If you have time for a PR including tests, I'll be grateful. Otherwise I can also take a look.
