### ISSUE TITLE
I would like to see support for more typing.

### ISSUE THREAD

**Issue by Bloodielie** [Neoteroi/rodi#9]
It would be cool to do support: Generic, Union, Sequence(List, Tuple...).

**Comment by RobertoPrevato** [comment]
Hi,
**Good news:** I started working on a branch to add support for `List[T]`, `Tuple[T]`, `Sequence[T]` from typing, and also the new syntax introduced in Python 3.9. I doubt it will be possible to make something complete for `Generic`.

This part is still being shaped in Python and not mature. Consider, since Python 3.9:

```
>>> from collections.abc import Sequence as CollSequence
>>> from typing import Sequence as TypeSequence

>>> CollSequence[str] is TypeSequence[str]
False

>>> from typing import List
>>> list[str] is List[str]
False
```

As a side note, I would love to make `rodi` typing-friendly, in the past I tried to make it type-friendly for the methods that activate concrete classes by their abstract classes - but at that time it wasn't easy to make something that didn't require a plugin for MyPy.

For example, I upvoted this comment a long time ago, which speaks exactly about the same use case: [https://github.com/python/mypy/issues/5374#issuecomment-436450801](https://github.com/python/mypy/issues/5374#issuecomment-436450801)

I checked again, while replying to your message, and the situation looks better now. However, MyPy still doesn't like abstract classes (this seems more caused by personal preference of MyPy's authors than an actual mistake in the desire of referring a concrete class by an abstract class).

For example, aside from the `type: ignore` and the `cast`, here at least the public API (register, inject) produces a nice result:

```python
from abc import ABC, abstractmethod

from typing import TypeVar, Type, Dict, cast


T_co = TypeVar("T_co", covariant=True)


REGISTER: Dict[Type[T_co], Type[T_co]] = {}


def register(interface: Type[T_co], implementation: Type[T_co]) -> None:
    REGISTER[interface] = implementation  # type: ignore


def inject(interface: Type[T_co]) -> T_co:
    concrete_type = REGISTER[interface]  # type: ignore
    activated_instance = concrete_type()  # type: ignore
    return cast(T_co, activated_instance)


class AbstractA(ABC):
    @abstractmethod
    def foo(self) -> str:
        pass


class BaseA(AbstractA):
    def foo(self) -> str:
        raise NotImplementedError


class ConcreteA(BaseA):
    def foo(self) -> str:
        return "Foo"


register(AbstractA, ConcreteA)  # MyPy doesn't like this and reports an error

register(BaseA, ConcreteA)  # this works - which is good! :)

x = inject(BaseA)  # this works, too, which is good for the user of inject method

x.foo()
```

**Comment by RobertoPrevato** [comment]
Done at 1.1.1
